<a href="https://colab.research.google.com/github/hinamehboobcs/Industry-Project/blob/main/Vanila_DQN_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Create project structure

import os

folders = [
    "project",
    "project/data"
]

for f in folders:
    os.makedirs(f, exist_ok=True)

files = [
    "config.py",
    "data_loader.py",
    "preprocessing.py",
    "feature_engineering.py",
    "scenario_generator.py",
    "environment.py",
    "reward_function.py",
    "dqn_model.py",
    "replay_buffer.py",
    "agent.py",
    "trainer.py",
    "scheduler.py",
    "evaluator.py",
    "utils.py"
]

for file in files:
    open(f"project/{file}", "w").close()

print("Project structure created")

Project structure created

In [4]:
#Testing Loading data
import sys

sys.path.append('/content/project')

from data_loader import DataLoader


loader = DataLoader(
    "/content/project/data/carers_available.csv",
    "/content/project/data/visits.csv"
)

carers, visits = loader.load_data()

print("Carers Shape:")
print(carers.shape)

print("\nVisits Shape:")
print(visits.shape)

print("\nCarers Columns:")
print(carers.columns)

print("\nVisits Columns:")
print(visits.columns)

Carers Shape:
(462, 23)

Visits Shape:
(3118, 15)

Carers Columns:
Index(['CarerID', 'WorkerType', 'Latitude', 'Longitude',
       'PreferredAreaLatitude', 'PreferredAreaLongitude',
       'MaxTravelDistanceMiles', 'ExperienceInYears', 'Skills', 'Gender',
       'Languages', 'VehicleType', 'WorkingDays', 'OffDays', 'ShiftStart',
       'ShiftEnd', 'ContractHoursPerWeek', 'MaxDailyHours', 'MaxWeeklyHours',
       'PreferredShift', 'Date', 'DayOfWeek', 'Status'],
      dtype='object')

Visits Columns:
Index(['VisitID', 'PatientID', 'Day', 'Latitude', 'Longitude',
       'VisitDurationMinutes', 'TimeWindowStart', 'TimeWindowEnd',
       'PriorityLevel', 'ComplexityLevel', 'RequiredSkills', 'PreferredGender',
       'PreferredLanguage', 'TwoCarerRequired', 'ContinuityRequirement'],
      dtype='object')

In [5]:
display(carers.head())
display(visits.head())

,CarerID,WorkerType,Latitude,Longitude,PreferredAreaLatitude,PreferredAreaLongitude,MaxTravelDistanceMiles,ExperienceInYears,Skills,Gender,...,OffDays,ShiftStart,ShiftEnd,ContractHoursPerWeek,MaxDailyHours,MaxWeeklyHours,PreferredShift,Date,DayOfWeek,Status
0,C0001,Student,51.372966,-0.357305,51.419129,-0.332031,5,1,"Medication Support, Palliative Care",Other,...,Sunday,07:00,13:00,20,5,20,Morning,01/06/2026,Monday,Available
1,C0001,Student,51.372966,-0.357305,51.419129,-0.332031,5,1,"Medication Support, Palliative Care",Other,...,Sunday,07:00,13:00,20,5,20,Morning,03/06/2026,Wednesday,Available
2,C0001,Student,51.372966,-0.357305,51.419129,-0.332031,5,1,"Medication Support, Palliative Care",Other,...,Sunday,07:00,13:00,20,5,20,Morning,05/06/2026,Friday,Available
3,C0001,Student,51.372966,-0.357305,51.419129,-0.332031,5,1,"Medication Support, Palliative Care",Other,...,Sunday,07:00,13:00,20,5,20,Morning,06/06/2026,Saturday,Available
4,C0002,Full-Time,51.310247,-0.362365,51.351372,-0.386422,8,8,"Dementia Care, Meal Preparation",Male,...,Flexible,14:00,18:00,40,9,45,Morning,01/06/2026,Monday,Available

,VisitID,PatientID,Day,Latitude,Longitude,VisitDurationMinutes,TimeWindowStart,TimeWindowEnd,PriorityLevel,ComplexityLevel,RequiredSkills,PreferredGender,PreferredLanguage,TwoCarerRequired,ContinuityRequirement
0,V000001,P0001,Tuesday,51.360080,-0.273553,45,15:00,18:00,Low,Low,"Companionship, Personal Care",No Preference,Arabic,No,Low
1,V000002,P0002,Tuesday,51.471417,-0.007311,45,10:00,13:00,Medium,Medium,Mobility Support,Female,Hindi,Yes,Medium
2,V000003,P0002,Wednesday,51.471417,-0.007311,45,10:00,13:00,Medium,Medium,Mobility Support,Female,Hindi,Yes,Medium
3,V000004,P0002,Saturday,51.471417,-0.007311,45,10:00,13:00,Medium,Medium,Mobility Support,Female,Hindi,Yes,Medium
4,V000005,P0002,Monday,51.471417,-0.007311,45,10:00,13:00,Medium,Medium,Mobility Support,Female,Hindi,Yes,Medium

In [6]:
#Check Dataset
print("Carers shape:", carers.shape)
print("Visits shape:", visits.shape)

print("\nNumber of unique carers:",
      carers['CarerID'].nunique())

print("Number of unique patients:",
      visits['PatientID'].nunique())

print("Number of unique visits:",
      visits['VisitID'].nunique())

Carers shape: (462, 23)
Visits shape: (3118, 15)

Number of unique carers: 100
Number of unique patients: 500
Number of unique visits: 3118

In [7]:
#Data Preprocessing checking
from preprocessing import DataPreprocessor

preprocessor = DataPreprocessor()

preprocessor.check_missing_values(
    carers,
    "Carers Dataset"
)

preprocessor.check_missing_values(
    visits,
    "Visits Dataset"
)

Carers Dataset
No missing values

Visits Dataset
No missing values

In [11]:
from preprocessing import DataPreprocessor

print(dir(DataPreprocessor))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'check_missing_values', 'convert_time_to_minutes', 'encode_column', 'normalize_coordinates']

In [12]:
import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import DataPreprocessor

In [13]:
print(dir(DataPreprocessor))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'check_missing_values', 'convert_time_columns', 'convert_time_to_minutes', 'encode_column', 'normalize_coordinates']

In [14]:
def convert_time_to_minutes(time_str):
    h, m = map(int, str(time_str).split(":"))
    return h*60 + m


# carers
carers["ShiftStart"] = carers["ShiftStart"].apply(
    convert_time_to_minutes
)

carers["ShiftEnd"] = carers["ShiftEnd"].apply(
    convert_time_to_minutes
)

# visits
visits["TimeWindowStart"] = visits[
    "TimeWindowStart"
].apply(convert_time_to_minutes)

visits["TimeWindowEnd"] = visits[
    "TimeWindowEnd"
].apply(convert_time_to_minutes)

In [15]:
print(
    carers[
        ["ShiftStart", "ShiftEnd"]
    ].head()
)

print()

print(
    visits[
        [
            "TimeWindowStart",
            "TimeWindowEnd"
        ]
    ].head()
)

   ShiftStart  ShiftEnd
0         420       780
1         420       780
2         420       780
3         420       780
4         840      1080

   TimeWindowStart  TimeWindowEnd
0              900           1080
1              600            780
2              600            780
3              600            780
4              600            780

In [16]:
print("Carers shape:", carers.shape)
print("Visits shape:", visits.shape)

print(
    "Unique carers:",
    carers["CarerID"].nunique()
)

print(
    "Unique visits:",
    visits["VisitID"].nunique()
)

Carers shape: (462, 23)
Visits shape: (3118, 15)
Unique carers: 100
Unique visits: 3118

In [22]:
import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import DataPreprocessor

preprocessor = DataPreprocessor()

In [24]:
def convert_time_to_minutes(self, time_str):

    try:
        if pd.isna(time_str):
            return 0

        time_str = str(time_str)

        # handle "07:00:00"
        parts = time_str.split(":")

        if len(parts) < 2:
            return int(parts[0]) * 60

        h = int(parts[0])
        m = int(parts[1])

        return h * 60 + m

    except:
        return 0

In [25]:
import importlib
import preprocessing

importlib.reload(preprocessing)

from preprocessing import DataPreprocessor

preprocessor = DataPreprocessor()

In [26]:
carers, visits = preprocessor.convert_time_columns(carers, visits)

ValueError: not enough values to unpack (expected 2, got 1)

In [27]:
print(carers[["ShiftStart","ShiftEnd"]].head())
print()
print(visits[["TimeWindowStart","TimeWindowEnd"]].head())

   ShiftStart  ShiftEnd
0         420       780
1         420       780
2         420       780
3         420       780
4         840      1080

   TimeWindowStart  TimeWindowEnd
0              900           1080
1              600            780
2              600            780
3              600            780
4              600            780

In [28]:
from feature_engineering import FeatureEngineer

engineer = FeatureEngineer()

distance_matrix = engineer.build_distance_matrix(carers, visits)

print(distance_matrix.shape)
print(distance_matrix[:3, :3])

(462, 3118)
[[ 5.98826736 26.62293117 26.62293117]
 [ 5.98826736 26.62293117 26.62293117]
 [ 5.98826736 26.62293117 26.62293117]]

In [29]:
from scenario_generator import ScenarioGenerator

sg = ScenarioGenerator()

new_visits = sg.cancel_visits(visits)

emergency = sg.generate_emergency_visit(visits)

print("Original visits:", len(visits))
print("After cancellation:", len(new_visits))

print("\nEmergency visit:")
print(emergency)

Original visits: 3118
After cancellation: 3028

Emergency visit:
None

In [32]:
import importlib
import environment

importlib.reload(environment)

from environment import CareEnv

In [33]:
env = CareEnv(carers, visits, distance_matrix)

state = env.reset()

print("State shape:", state.shape)

State shape: (7,)

In [35]:
import importlib
import environment
importlib.reload(environment)

from environment import CareEnv

In [37]:
env = CareEnv(carers, visits, distance_matrix)

state = env.reset()

next_state, reward, done, _ = env.step(0)

print("State shape:", state.shape)
print("Next state shape:", next_state.shape)
print("Reward:", reward)
print("Done:", done)

State shape: (7,)
Next state shape: (7,)
Reward: -5.988267355854858
Done: False

In [38]:
from replay_buffer import ReplayBuffer

buffer = ReplayBuffer()

state = env.reset()

next_state, reward, done, _ = env.step(0)

buffer.push(state, 0, reward, next_state, done)

print("Buffer size:", len(buffer))

sample = buffer.sample(1)

print("Sample states shape:", sample[0].shape)

Buffer size: 1
Sample states shape: (1, 7)

In [39]:
import torch
from dqn_model import DQN

state_dim = 7
action_dim = len(carers)

model = DQN(state_dim, action_dim)

state = torch.FloatTensor(state)

q_values = model(state)

print("Q-values shape:", q_values.shape)

Q-values shape: torch.Size([462])

In [40]:
#testing Agent
from agent import DQNAgent

agent = DQNAgent(state_dim=7, action_dim=len(carers))

state = env.reset()

action = agent.select_action(state)

print("Selected action:", action)
print("Epsilon:", agent.epsilon)

Selected action: 262
Epsilon: 1.0

In [41]:
#Testing Training
from trainer import Trainer
from replay_buffer import ReplayBuffer
from agent import DQNAgent
from environment import CareEnv

env = CareEnv(carers, visits, distance_matrix)

agent = DQNAgent(state_dim=7, action_dim=len(carers))

buffer = ReplayBuffer()

trainer = Trainer(env, agent, buffer)

rewards = trainer.train(episodes=3)

print("Training complete")

Episode 1, Reward: -85236.21, Epsilon: 0.995
Episode 2, Reward: -85084.48, Epsilon: 0.990
Episode 3, Reward: -83738.99, Epsilon: 0.985
Training complete

In [48]:
#evaluation
from evaluator import Evaluator

evaluator = Evaluator(env)

metrics = evaluator.evaluate(
    total_distance=1000,
    max_possible_distance=5000
)

print(metrics)

{'workload_variance': np.float64(44503.939323663355), 'workload_std': np.float64(210.9595679832118), 'mean_workload': np.float64(502.3051948051948), 'fairness_index': np.float64(0.8500614117144515), 'coverage': 1.0, 'distance_efficiency': 0.8000000000004}

In [49]:
from evaluator import Evaluator

evaluator = Evaluator(env)

metrics = evaluator.evaluate(
    total_distance=1000,
    max_possible_distance=5000
)

print(metrics)

{'workload_variance': np.float64(44503.939323663355), 'workload_std': np.float64(210.9595679832118), 'mean_workload': np.float64(502.3051948051948), 'fairness_index': np.float64(0.8500614117144515), 'coverage': 1.0, 'distance_efficiency': 0.8000000000004}

In [50]:
metrics = evaluator.evaluate(
    total_distance=1000,
    max_possible_distance=5000
)

print(metrics)

{'workload_variance': np.float64(44503.939323663355), 'workload_std': np.float64(210.9595679832118), 'mean_workload': np.float64(502.3051948051948), 'fairness_index': np.float64(0.8500614117144515), 'coverage': 1.0, 'distance_efficiency': 0.8000000000004}

In [51]:
import importlib
import evaluator

importlib.reload(evaluator)

In [52]:
from evaluator import Evaluator

evaluator_obj = Evaluator(env)

In [53]:
metrics = evaluator_obj.evaluate(
    total_distance=1000,
    max_possible_distance=5000
)

print(metrics)

{'workload_variance': np.float64(44503.939323663355), 'workload_std': np.float64(210.9595679832118), 'mean_workload': np.float64(502.3051948051948), 'fairness_index': np.float64(0.8500614117144515), 'coverage': 1.0, 'distance_efficiency': 0.8000000000004}

In [58]:
import pandas as pd

df = pd.DataFrame([metrics])

df = df[
    [
        "workload_variance",
        "workload_std",
        "fairness_index",
        "distance_efficiency",
        "coverage"
    ]
]

df.to_csv("final_metrics.csv", index=False)

print("Saved final_metrics.csv")
df

Saved final_metrics.csv

,workload_variance,workload_std,fairness_index,distance_efficiency,coverage
0,44503.939324,210.959568,0.850061,0.8,1.0

In [57]:
import importlib
import evaluator

importlib.reload(evaluator)